name: dev
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  syncfusion_flutter_calendar: ^20.2.40
  flutter_timezone: ^1.0.7
  table_calendar: ^3.0.8
  google_sign_in: ^5.2.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  firebase_core: ^2.16.0
  flutter_local_notifications: ^15.1.1  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/google.png
    - lib/images/apple.png
